apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

images:
  - name: queryforge-text2sql
    newName: queryforge-text2sql
    newTag: latest

